name: INFRASTRUCTURE-PROVISIONING
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
  push:
    branches:
      - main
      - develop
    paths:
      - "terraform/**"
      - ".github/workflows/infrastructure-provisioning.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "terraform/**"
      - ".github/workflows/infrastructure-provisioning.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

env:
  TF_IN_AUTOMATION: true
  TERRAFORM_VERSION: "1.1.7"

jobs:
  determine_environment:
    name: "Determine Environment"
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get_env.outputs.environment }}
      dir: ${{ steps.get_env.outputs.dir }}
    steps:
      - id: get_env
        name: Set environment for this workflow run
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "dir=./terraform/environments/development" >> $GITHUB_OUTPUT
          else
            ENVIRONMENT="${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'development') }}"
            echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
            echo "dir=./terraform/environments/$ENVIRONMENT" >> $GITHUB_OUTPUT
          fi

  call-reusable-terraform:
    name: "Execute Terraform Core Logic"
    needs: determine_environment

    uses: ./.github/workflows/reusable-terraform-core.yml

    with:
      environment: ${{ needs.determine_environment.outputs.environment }}
      terraform_directory: ${{ needs.determine_environment.outputs.dir }}
      is_pull_request: ${{ github.event_name == 'pull_request' }}

    secrets:
      GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
